/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AppMarketListing {
  'title' : string,
  'thumbnail' : string,
  'tagline' : string,
  'preview' : AppStorePreview,
  'tags' : Array<string>,
  'showcaseVisuals' : Array<string>,
  'description' : string,
}
export interface AppStorePreview {
  'featuresSection' : Array<FeatureSection>,
  'heroSection' : HeroSection,
  'callToAction' : CallToAction,
  'subjectsSection' : Array<SubjectSection>,
}
export interface Assignment {
  'lessonId' : LessonId,
  'title' : string,
  'studentId' : StudentId,
  'assignedBy' : TeacherId,
  'completed' : boolean,
  'dueDate' : Time,
  'description' : string,
  'grade' : [] | [bigint],
  'assignmentId' : AssignmentId,
  'submission' : [] | [string],
}
export type AssignmentId = bigint;
export interface CallToAction {
  'premiumInfo' : PremiumInfo,
  'message' : string,
}
export interface CoreFeature {
  'icon' : string,
  'name' : string,
  'description' : string,
}
export interface FeatureSection {
  'icon' : string,
  'name' : string,
  'description' : string,
}
export type GradeLevel = bigint;
export interface HeroSection {
  'title' : string,
  'tagline' : string,
  'image' : string,
}
export type LessonId = bigint;
export interface LessonPlan {
  'lessonId' : LessonId,
  'title' : string,
  'content' : string,
  'assignedTo' : Array<StudentId>,
  'subject' : Subject,
  'gradeLevel' : GradeLevel,
  'fromLibrary' : boolean,
}
export interface LessonPlanDraft { 'title' : string, 'content' : string }
export interface LessonPlanRequest {
  'topic' : [] | [string],
  'constraints' : [] | [string],
  'subject' : string,
  'standards' : [] | [string],
  'gradeLevel' : bigint,
}
export interface NavigationInstructions {
  'skipButton' : string,
  'progressIndicator' : string,
  'nextButton' : string,
}
export interface OnboardingGuide {
  'coreFeatures' : Array<CoreFeature>,
  'mainTitle' : string,
  'navigationInstructions' : NavigationInstructions,
  'introText' : string,
  'subjectsOverview' : Array<SubjectOverview>,
  'premiumUpgrade' : PremiumUpgradeSection,
}
export interface PreMadeLesson {
  'lessonId' : LessonId,
  'title' : string,
  'content' : string,
  'subject' : Subject,
  'gradeLevel' : GradeLevel,
}
export interface PremiumInfo {
  'cancellationPolicy' : string,
  'benefits' : Array<string>,
  'price' : string,
}
export interface PremiumUpgradeSection {
  'title' : string,
  'cancellationPolicy' : string,
  'description' : string,
  'benefits' : Array<string>,
  'price' : string,
}
export type PublicationStatus = { 'published' : { 'publicationTime' : Time } } |
  { 'unpublished' : { 'reason' : string } };
export interface ReportCard {
  'issueDate' : Time,
  'overallAverage' : number,
  'studentId' : StudentId,
  'subjects' : Array<SubjectGrades>,
  'validUntil' : Time,
  'reportCardId' : ReportCardId,
}
export type ReportCardId = bigint;
export interface ShoppingItem {
  'productName' : string,
  'currency' : string,
  'quantity' : bigint,
  'priceInCents' : bigint,
  'productDescription' : string,
}
export interface StripeConfiguration {
  'allowedCountries' : Array<string>,
  'secretKey' : string,
}
export type StripeSessionStatus = {
    'completed' : { 'userPrincipal' : [] | [string], 'response' : string }
  } |
  { 'failed' : { 'error' : string } };
export type StudentId = Principal;
export interface Subject { 'name' : string, 'subjectId' : bigint }
export interface SubjectGrades {
  'grades' : Array<bigint>,
  'subject' : Subject,
  'average' : number,
}
export interface SubjectOverview {
  'icon' : string,
  'name' : string,
  'description' : string,
}
export interface SubjectSection { 'icon' : string, 'name' : string }
export type TeacherId = Principal;
export type Time = bigint;
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface UserProfile { 'name' : string, 'role' : UserRole }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'assignLessonToStudent' : ActorMethod<
    [string, LessonId, string, Time, StudentId],
    AssignmentId
  >,
  'cancelPremiumSubscription' : ActorMethod<[], string>,
  'createCheckoutSession' : ActorMethod<
    [Array<ShoppingItem>, string, string],
    string
  >,
  'createCustomLesson' : ActorMethod<
    [string, Subject, GradeLevel, string],
    LessonId
  >,
  'createLessonFromLibrary' : ActorMethod<[LessonId], LessonId>,
  'generateAiLessonPlanDraft' : ActorMethod<
    [LessonPlanRequest],
    LessonPlanDraft
  >,
  'generateReportCard' : ActorMethod<[StudentId], ReportCardId>,
  'getAllReportCardsForStudent' : ActorMethod<[StudentId], Array<ReportCard>>,
  'getAppMarketListing' : ActorMethod<[], AppMarketListing>,
  'getAppStorePreview' : ActorMethod<[], AppStorePreview>,
  'getAssignmentsBySubject' : ActorMethod<
    [StudentId, bigint],
    Array<Assignment>
  >,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getGradeAveragesBySubject' : ActorMethod<[StudentId, bigint], bigint>,
  'getLessonAssignmentDetails' : ActorMethod<
    [AssignmentId],
    [] | [[string, string, string, Time]]
  >,
  'getLessonAverageBySubject' : ActorMethod<[StudentId, bigint], bigint>,
  'getLessonContent' : ActorMethod<[LessonId], string>,
  'getOnboardingGuide' : ActorMethod<[], OnboardingGuide>,
  'getPreMadeLessons' : ActorMethod<[], Array<PreMadeLesson>>,
  'getPremiumAccessStatus' : ActorMethod<[Principal], boolean>,
  'getPublicationStatus' : ActorMethod<[], PublicationStatus>,
  'getReportCard' : ActorMethod<[ReportCardId], ReportCard>,
  'getStripeSessionStatus' : ActorMethod<[string], StripeSessionStatus>,
  'getStudentAssignments' : ActorMethod<[StudentId], Array<Assignment>>,
  'getStudentReportCards' : ActorMethod<[StudentId], Array<ReportCard>>,
  'getSubjects' : ActorMethod<[], Array<Subject>>,
  'getUnpublishReason' : ActorMethod<[], [] | [string]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'gradeAssignment' : ActorMethod<[AssignmentId, bigint], undefined>,
  'grantPremiumAccess' : ActorMethod<[Principal], undefined>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isPublished' : ActorMethod<[], boolean>,
  'isStripeConfigured' : ActorMethod<[], boolean>,
  'isSubscriptionCancelled' : ActorMethod<[Principal], boolean>,
  'listAllLessonPlans' : ActorMethod<[], Array<LessonPlan>>,
  'publishApp' : ActorMethod<[], undefined>,
  'purchasePremiumAccess' : ActorMethod<[], string>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'setStripeConfiguration' : ActorMethod<[StripeConfiguration], undefined>,
  'submitAssignment' : ActorMethod<[AssignmentId, string], undefined>,
  'submitAssignmentWithGrade' : ActorMethod<
    [AssignmentId, string, bigint],
    undefined
  >,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
  'unpublishApp' : ActorMethod<[string], undefined>,
  'viewLessonsByGrade' : ActorMethod<[GradeLevel], Array<LessonPlan>>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];