/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const LessonId = IDL.Nat;
export const Time = IDL.Int;
export const StudentId = IDL.Principal;
export const AssignmentId = IDL.Nat;
export const ShoppingItem = IDL.Record({
  'productName' : IDL.Text,
  'currency' : IDL.Text,
  'quantity' : IDL.Nat,
  'priceInCents' : IDL.Nat,
  'productDescription' : IDL.Text,
});
export const Subject = IDL.Record({ 'name' : IDL.Text, 'subjectId' : IDL.Nat });
export const GradeLevel = IDL.Nat;
export const LessonPlanRequest = IDL.Record({
  'topic' : IDL.Opt(IDL.Text),
  'constraints' : IDL.Opt(IDL.Text),
  'subject' : IDL.Text,
  'standards' : IDL.Opt(IDL.Text),
  'gradeLevel' : IDL.Nat,
});
export const LessonPlanDraft = IDL.Record({
  'title' : IDL.Text,
  'content' : IDL.Text,
});
export const ReportCardId = IDL.Nat;
export const SubjectGrades = IDL.Record({
  'grades' : IDL.Vec(IDL.Nat),
  'subject' : Subject,
  'average' : IDL.Float64,
});
export const ReportCard = IDL.Record({
  'issueDate' : Time,
  'overallAverage' : IDL.Float64,
  'studentId' : StudentId,
  'subjects' : IDL.Vec(SubjectGrades),
  'validUntil' : Time,
  'reportCardId' : ReportCardId,
});
export const FeatureSection = IDL.Record({
  'icon' : IDL.Text,
  'name' : IDL.Text,
  'description' : IDL.Text,
});
export const HeroSection = IDL.Record({
  'title' : IDL.Text,
  'tagline' : IDL.Text,
  'image' : IDL.Text,
});
export const PremiumInfo = IDL.Record({
  'cancellationPolicy' : IDL.Text,
  'benefits' : IDL.Vec(IDL.Text),
  'price' : IDL.Text,
});
export const CallToAction = IDL.Record({
  'premiumInfo' : PremiumInfo,
  'message' : IDL.Text,
});
export const SubjectSection = IDL.Record({
  'icon' : IDL.Text,
  'name' : IDL.Text,
});
export const AppStorePreview = IDL.Record({
  'featuresSection' : IDL.Vec(FeatureSection),
  'heroSection' : HeroSection,
  'callToAction' : CallToAction,
  'subjectsSection' : IDL.Vec(SubjectSection),
});
export const AppMarketListing = IDL.Record({
  'title' : IDL.Text,
  'thumbnail' : IDL.Text,
  'tagline' : IDL.Text,
  'preview' : AppStorePreview,
  'tags' : IDL.Vec(IDL.Text),
  'showcaseVisuals' : IDL.Vec(IDL.Text),
  'description' : IDL.Text,
});
export const TeacherId = IDL.Principal;
export const Assignment = IDL.Record({
  'lessonId' : LessonId,
  'title' : IDL.Text,
  'studentId' : StudentId,
  'assignedBy' : TeacherId,
  'completed' : IDL.Bool,
  'dueDate' : Time,
  'description' : IDL.Text,
  'grade' : IDL.Opt(IDL.Nat),
  'assignmentId' : AssignmentId,
  'submission' : IDL.Opt(IDL.Text),
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text, 'role' : UserRole });
export const CoreFeature = IDL.Record({
  'icon' : IDL.Text,
  'name' : IDL.Text,
  'description' : IDL.Text,
});
export const NavigationInstructions = IDL.Record({
  'skipButton' : IDL.Text,
  'progressIndicator' : IDL.Text,
  'nextButton' : IDL.Text,
});
export const SubjectOverview = IDL.Record({
  'icon' : IDL.Text,
  'name' : IDL.Text,
  'description' : IDL.Text,
});
export const PremiumUpgradeSection = IDL.Record({
  'title' : IDL.Text,
  'cancellationPolicy' : IDL.Text,
  'description' : IDL.Text,
  'benefits' : IDL.Vec(IDL.Text),
  'price' : IDL.Text,
});
export const OnboardingGuide = IDL.Record({
  'coreFeatures' : IDL.Vec(CoreFeature),
  'mainTitle' : IDL.Text,
  'navigationInstructions' : NavigationInstructions,
  'introText' : IDL.Text,
  'subjectsOverview' : IDL.Vec(SubjectOverview),
  'premiumUpgrade' : PremiumUpgradeSection,
});
export const PreMadeLesson = IDL.Record({
  'lessonId' : LessonId,
  'title' : IDL.Text,
  'content' : IDL.Text,
  'subject' : Subject,
  'gradeLevel' : GradeLevel,
});
export const PublicationStatus = IDL.Variant({
  'published' : IDL.Record({ 'publicationTime' : Time }),
  'unpublished' : IDL.Record({ 'reason' : IDL.Text }),
});
export const StripeSessionStatus = IDL.Variant({
  'completed' : IDL.Record({
    'userPrincipal' : IDL.Opt(IDL.Text),
    'response' : IDL.Text,
  }),
  'failed' : IDL.Record({ 'error' : IDL.Text }),
});
export const LessonPlan = IDL.Record({
  'lessonId' : LessonId,
  'title' : IDL.Text,
  'content' : IDL.Text,
  'assignedTo' : IDL.Vec(StudentId),
  'subject' : Subject,
  'gradeLevel' : GradeLevel,
  'fromLibrary' : IDL.Bool,
});
export const StripeConfiguration = IDL.Record({
  'allowedCountries' : IDL.Vec(IDL.Text),
  'secretKey' : IDL.Text,
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'assignLessonToStudent' : IDL.Func(
      [IDL.Text, LessonId, IDL.Text, Time, StudentId],
      [AssignmentId],
      [],
    ),
  'cancelPremiumSubscription' : IDL.Func([], [IDL.Text], []),
  'createCheckoutSession' : IDL.Func(
      [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text],
      [IDL.Text],
      [],
    ),
  'createCustomLesson' : IDL.Func(
      [IDL.Text, Subject, GradeLevel, IDL.Text],
      [LessonId],
      [],
    ),
  'createLessonFromLibrary' : IDL.Func([LessonId], [LessonId], []),
  'generateAiLessonPlanDraft' : IDL.Func(
      [LessonPlanRequest],
      [LessonPlanDraft],
      ['query'],
    ),
  'generateReportCard' : IDL.Func([StudentId], [ReportCardId], []),
  'getAllReportCardsForStudent' : IDL.Func(
      [StudentId],
      [IDL.Vec(ReportCard)],
      ['query'],
    ),
  'getAppMarketListing' : IDL.Func([], [AppMarketListing], ['query']),
  'getAppStorePreview' : IDL.Func([], [AppStorePreview], ['query']),
  'getAssignmentsBySubject' : IDL.Func(
      [StudentId, IDL.Nat],
      [IDL.Vec(Assignment)],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getGradeAveragesBySubject' : IDL.Func(
      [StudentId, IDL.Nat],
      [IDL.Nat],
      ['query'],
    ),
  'getLessonAssignmentDetails' : IDL.Func(
      [AssignmentId],
      [IDL.Opt(IDL.Tuple(IDL.Text, IDL.Text, IDL.Text, Time))],
      ['query'],
    ),
  'getLessonAverageBySubject' : IDL.Func(
      [StudentId, IDL.Nat],
      [IDL.Nat],
      ['query'],
    ),
  'getLessonContent' : IDL.Func([LessonId], [IDL.Text], ['query']),
  'getOnboardingGuide' : IDL.Func([], [OnboardingGuide], ['query']),
  'getPreMadeLessons' : IDL.Func([], [IDL.Vec(PreMadeLesson)], ['query']),
  'getPremiumAccessStatus' : IDL.Func([IDL.Principal], [IDL.Bool], ['query']),
  'getPublicationStatus' : IDL.Func([], [PublicationStatus], ['query']),
  'getReportCard' : IDL.Func([ReportCardId], [ReportCard], ['query']),
  'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
  'getStudentAssignments' : IDL.Func(
      [StudentId],
      [IDL.Vec(Assignment)],
      ['query'],
    ),
  'getStudentReportCards' : IDL.Func(
      [StudentId],
      [IDL.Vec(ReportCard)],
      ['query'],
    ),
  'getSubjects' : IDL.Func([], [IDL.Vec(Subject)], ['query']),
  'getUnpublishReason' : IDL.Func([], [IDL.Opt(IDL.Text)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'gradeAssignment' : IDL.Func([AssignmentId, IDL.Nat], [], []),
  'grantPremiumAccess' : IDL.Func([IDL.Principal], [], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isPublished' : IDL.Func([], [IDL.Bool], ['query']),
  'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
  'isSubscriptionCancelled' : IDL.Func([IDL.Principal], [IDL.Bool], ['query']),
  'listAllLessonPlans' : IDL.Func([], [IDL.Vec(LessonPlan)], ['query']),
  'publishApp' : IDL.Func([], [], []),
  'purchasePremiumAccess' : IDL.Func([], [IDL.Text], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
  'submitAssignment' : IDL.Func([AssignmentId, IDL.Text], [], []),
  'submitAssignmentWithGrade' : IDL.Func(
      [AssignmentId, IDL.Text, IDL.Nat],
      [],
      [],
    ),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'unpublishApp' : IDL.Func([IDL.Text], [], []),
  'viewLessonsByGrade' : IDL.Func(
      [GradeLevel],
      [IDL.Vec(LessonPlan)],
      ['query'],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const LessonId = IDL.Nat;
  const Time = IDL.Int;
  const StudentId = IDL.Principal;
  const AssignmentId = IDL.Nat;
  const ShoppingItem = IDL.Record({
    'productName' : IDL.Text,
    'currency' : IDL.Text,
    'quantity' : IDL.Nat,
    'priceInCents' : IDL.Nat,
    'productDescription' : IDL.Text,
  });
  const Subject = IDL.Record({ 'name' : IDL.Text, 'subjectId' : IDL.Nat });
  const GradeLevel = IDL.Nat;
  const LessonPlanRequest = IDL.Record({
    'topic' : IDL.Opt(IDL.Text),
    'constraints' : IDL.Opt(IDL.Text),
    'subject' : IDL.Text,
    'standards' : IDL.Opt(IDL.Text),
    'gradeLevel' : IDL.Nat,
  });
  const LessonPlanDraft = IDL.Record({
    'title' : IDL.Text,
    'content' : IDL.Text,
  });
  const ReportCardId = IDL.Nat;
  const SubjectGrades = IDL.Record({
    'grades' : IDL.Vec(IDL.Nat),
    'subject' : Subject,
    'average' : IDL.Float64,
  });
  const ReportCard = IDL.Record({
    'issueDate' : Time,
    'overallAverage' : IDL.Float64,
    'studentId' : StudentId,
    'subjects' : IDL.Vec(SubjectGrades),
    'validUntil' : Time,
    'reportCardId' : ReportCardId,
  });
  const FeatureSection = IDL.Record({
    'icon' : IDL.Text,
    'name' : IDL.Text,
    'description' : IDL.Text,
  });
  const HeroSection = IDL.Record({
    'title' : IDL.Text,
    'tagline' : IDL.Text,
    'image' : IDL.Text,
  });
  const PremiumInfo = IDL.Record({
    'cancellationPolicy' : IDL.Text,
    'benefits' : IDL.Vec(IDL.Text),
    'price' : IDL.Text,
  });
  const CallToAction = IDL.Record({
    'premiumInfo' : PremiumInfo,
    'message' : IDL.Text,
  });
  const SubjectSection = IDL.Record({ 'icon' : IDL.Text, 'name' : IDL.Text });
  const AppStorePreview = IDL.Record({
    'featuresSection' : IDL.Vec(FeatureSection),
    'heroSection' : HeroSection,
    'callToAction' : CallToAction,
    'subjectsSection' : IDL.Vec(SubjectSection),
  });
  const AppMarketListing = IDL.Record({
    'title' : IDL.Text,
    'thumbnail' : IDL.Text,
    'tagline' : IDL.Text,
    'preview' : AppStorePreview,
    'tags' : IDL.Vec(IDL.Text),
    'showcaseVisuals' : IDL.Vec(IDL.Text),
    'description' : IDL.Text,
  });
  const TeacherId = IDL.Principal;
  const Assignment = IDL.Record({
    'lessonId' : LessonId,
    'title' : IDL.Text,
    'studentId' : StudentId,
    'assignedBy' : TeacherId,
    'completed' : IDL.Bool,
    'dueDate' : Time,
    'description' : IDL.Text,
    'grade' : IDL.Opt(IDL.Nat),
    'assignmentId' : AssignmentId,
    'submission' : IDL.Opt(IDL.Text),
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text, 'role' : UserRole });
  const CoreFeature = IDL.Record({
    'icon' : IDL.Text,
    'name' : IDL.Text,
    'description' : IDL.Text,
  });
  const NavigationInstructions = IDL.Record({
    'skipButton' : IDL.Text,
    'progressIndicator' : IDL.Text,
    'nextButton' : IDL.Text,
  });
  const SubjectOverview = IDL.Record({
    'icon' : IDL.Text,
    'name' : IDL.Text,
    'description' : IDL.Text,
  });
  const PremiumUpgradeSection = IDL.Record({
    'title' : IDL.Text,
    'cancellationPolicy' : IDL.Text,
    'description' : IDL.Text,
    'benefits' : IDL.Vec(IDL.Text),
    'price' : IDL.Text,
  });
  const OnboardingGuide = IDL.Record({
    'coreFeatures' : IDL.Vec(CoreFeature),
    'mainTitle' : IDL.Text,
    'navigationInstructions' : NavigationInstructions,
    'introText' : IDL.Text,
    'subjectsOverview' : IDL.Vec(SubjectOverview),
    'premiumUpgrade' : PremiumUpgradeSection,
  });
  const PreMadeLesson = IDL.Record({
    'lessonId' : LessonId,
    'title' : IDL.Text,
    'content' : IDL.Text,
    'subject' : Subject,
    'gradeLevel' : GradeLevel,
  });
  const PublicationStatus = IDL.Variant({
    'published' : IDL.Record({ 'publicationTime' : Time }),
    'unpublished' : IDL.Record({ 'reason' : IDL.Text }),
  });
  const StripeSessionStatus = IDL.Variant({
    'completed' : IDL.Record({
      'userPrincipal' : IDL.Opt(IDL.Text),
      'response' : IDL.Text,
    }),
    'failed' : IDL.Record({ 'error' : IDL.Text }),
  });
  const LessonPlan = IDL.Record({
    'lessonId' : LessonId,
    'title' : IDL.Text,
    'content' : IDL.Text,
    'assignedTo' : IDL.Vec(StudentId),
    'subject' : Subject,
    'gradeLevel' : GradeLevel,
    'fromLibrary' : IDL.Bool,
  });
  const StripeConfiguration = IDL.Record({
    'allowedCountries' : IDL.Vec(IDL.Text),
    'secretKey' : IDL.Text,
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'assignLessonToStudent' : IDL.Func(
        [IDL.Text, LessonId, IDL.Text, Time, StudentId],
        [AssignmentId],
        [],
      ),
    'cancelPremiumSubscription' : IDL.Func([], [IDL.Text], []),
    'createCheckoutSession' : IDL.Func(
        [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text],
        [IDL.Text],
        [],
      ),
    'createCustomLesson' : IDL.Func(
        [IDL.Text, Subject, GradeLevel, IDL.Text],
        [LessonId],
        [],
      ),
    'createLessonFromLibrary' : IDL.Func([LessonId], [LessonId], []),
    'generateAiLessonPlanDraft' : IDL.Func(
        [LessonPlanRequest],
        [LessonPlanDraft],
        ['query'],
      ),
    'generateReportCard' : IDL.Func([StudentId], [ReportCardId], []),
    'getAllReportCardsForStudent' : IDL.Func(
        [StudentId],
        [IDL.Vec(ReportCard)],
        ['query'],
      ),
    'getAppMarketListing' : IDL.Func([], [AppMarketListing], ['query']),
    'getAppStorePreview' : IDL.Func([], [AppStorePreview], ['query']),
    'getAssignmentsBySubject' : IDL.Func(
        [StudentId, IDL.Nat],
        [IDL.Vec(Assignment)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getGradeAveragesBySubject' : IDL.Func(
        [StudentId, IDL.Nat],
        [IDL.Nat],
        ['query'],
      ),
    'getLessonAssignmentDetails' : IDL.Func(
        [AssignmentId],
        [IDL.Opt(IDL.Tuple(IDL.Text, IDL.Text, IDL.Text, Time))],
        ['query'],
      ),
    'getLessonAverageBySubject' : IDL.Func(
        [StudentId, IDL.Nat],
        [IDL.Nat],
        ['query'],
      ),
    'getLessonContent' : IDL.Func([LessonId], [IDL.Text], ['query']),
    'getOnboardingGuide' : IDL.Func([], [OnboardingGuide], ['query']),
    'getPreMadeLessons' : IDL.Func([], [IDL.Vec(PreMadeLesson)], ['query']),
    'getPremiumAccessStatus' : IDL.Func([IDL.Principal], [IDL.Bool], ['query']),
    'getPublicationStatus' : IDL.Func([], [PublicationStatus], ['query']),
    'getReportCard' : IDL.Func([ReportCardId], [ReportCard], ['query']),
    'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
    'getStudentAssignments' : IDL.Func(
        [StudentId],
        [IDL.Vec(Assignment)],
        ['query'],
      ),
    'getStudentReportCards' : IDL.Func(
        [StudentId],
        [IDL.Vec(ReportCard)],
        ['query'],
      ),
    'getSubjects' : IDL.Func([], [IDL.Vec(Subject)], ['query']),
    'getUnpublishReason' : IDL.Func([], [IDL.Opt(IDL.Text)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'gradeAssignment' : IDL.Func([AssignmentId, IDL.Nat], [], []),
    'grantPremiumAccess' : IDL.Func([IDL.Principal], [], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isPublished' : IDL.Func([], [IDL.Bool], ['query']),
    'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
    'isSubscriptionCancelled' : IDL.Func(
        [IDL.Principal],
        [IDL.Bool],
        ['query'],
      ),
    'listAllLessonPlans' : IDL.Func([], [IDL.Vec(LessonPlan)], ['query']),
    'publishApp' : IDL.Func([], [], []),
    'purchasePremiumAccess' : IDL.Func([], [IDL.Text], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
    'submitAssignment' : IDL.Func([AssignmentId, IDL.Text], [], []),
    'submitAssignmentWithGrade' : IDL.Func(
        [AssignmentId, IDL.Text, IDL.Nat],
        [],
        [],
      ),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'unpublishApp' : IDL.Func([IDL.Text], [], []),
    'viewLessonsByGrade' : IDL.Func(
        [GradeLevel],
        [IDL.Vec(LessonPlan)],
        ['query'],
      ),
  });
};

export const init = ({ IDL }) => { return []; };