/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface PreMadeLesson {
    lessonId: LessonId;
    title: string;
    content: string;
    subject: Subject;
    gradeLevel: GradeLevel;
}
export interface PremiumInfo {
    cancellationPolicy: string;
    benefits: Array<string>;
    price: string;
}
export interface TransformationOutput {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export type Time = bigint;
export interface SubjectSection {
    icon: string;
    name: string;
}
export interface ReportCard {
    issueDate: Time;
    overallAverage: number;
    studentId: StudentId;
    subjects: Array<SubjectGrades>;
    validUntil: Time;
    reportCardId: ReportCardId;
}
export interface NavigationInstructions {
    skipButton: string;
    progressIndicator: string;
    nextButton: string;
}
export type GradeLevel = bigint;
export interface HeroSection {
    title: string;
    tagline: string;
    image: string;
}
export interface CallToAction {
    premiumInfo: PremiumInfo;
    message: string;
}
export interface FeatureSection {
    icon: string;
    name: string;
    description: string;
}
export interface SubjectOverview {
    icon: string;
    name: string;
    description: string;
}
export interface LessonPlan {
    lessonId: LessonId;
    title: string;
    content: string;
    assignedTo: Array<StudentId>;
    subject: Subject;
    gradeLevel: GradeLevel;
    fromLibrary: boolean;
}
export interface TransformationInput {
    context: Uint8Array;
    response: http_request_result;
}
export interface PremiumUpgradeSection {
    title: string;
    cancellationPolicy: string;
    description: string;
    benefits: Array<string>;
    price: string;
}
export type AssignmentId = bigint;
export interface Assignment {
    lessonId: LessonId;
    title: string;
    studentId: StudentId;
    assignedBy: TeacherId;
    completed: boolean;
    dueDate: Time;
    description: string;
    grade?: bigint;
    assignmentId: AssignmentId;
    submission?: string;
}
export type StripeSessionStatus = {
    __kind__: "completed";
    completed: {
        userPrincipal?: string;
        response: string;
    };
} | {
    __kind__: "failed";
    failed: {
        error: string;
    };
};
export interface StripeConfiguration {
    allowedCountries: Array<string>;
    secretKey: string;
}
export interface Subject {
    name: string;
    subjectId: bigint;
}
export type LessonId = bigint;
export interface OnboardingGuide {
    coreFeatures: Array<CoreFeature>;
    mainTitle: string;
    navigationInstructions: NavigationInstructions;
    introText: string;
    subjectsOverview: Array<SubjectOverview>;
    premiumUpgrade: PremiumUpgradeSection;
}
export type PublicationStatus = {
    __kind__: "published";
    published: {
        publicationTime: Time;
    };
} | {
    __kind__: "unpublished";
    unpublished: {
        reason: string;
    };
};
export type StudentId = Principal;
export type TeacherId = Principal;
export interface http_request_result {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export interface SubjectGrades {
    grades: Array<bigint>;
    subject: Subject;
    average: number;
}
export interface http_header {
    value: string;
    name: string;
}
export interface ShoppingItem {
    productName: string;
    currency: string;
    quantity: bigint;
    priceInCents: bigint;
    productDescription: string;
}
export interface CoreFeature {
    icon: string;
    name: string;
    description: string;
}
export interface AppMarketListing {
    title: string;
    thumbnail: string;
    tagline: string;
    preview: AppStorePreview;
    tags: Array<string>;
    showcaseVisuals: Array<string>;
    description: string;
}
export type ReportCardId = bigint;
export interface AppStorePreview {
    featuresSection: Array<FeatureSection>;
    heroSection: HeroSection;
    callToAction: CallToAction;
    subjectsSection: Array<SubjectSection>;
}
export interface UserProfile {
    name: string;
    role: UserRole;
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    assignLessonToStudent(assignmentTitle: string, lessonId: LessonId, description: string, dueDate: Time, studentId: StudentId): Promise<AssignmentId>;
    cancelPremiumSubscription(): Promise<string>;
    createCheckoutSession(items: Array<ShoppingItem>, successUrl: string, cancelUrl: string): Promise<string>;
    createCustomLesson(title: string, subject: Subject, gradeLevel: GradeLevel, content: string): Promise<LessonId>;
    createLessonFromLibrary(libraryLessonId: LessonId): Promise<LessonId>;
    generateReportCard(studentId: StudentId): Promise<ReportCardId>;
    getAllReportCardsForStudent(studentId: StudentId): Promise<Array<ReportCard>>;
    getAppMarketListing(): Promise<AppMarketListing>;
    getAppStorePreview(): Promise<AppStorePreview>;
    getAssignmentsBySubject(studentId: StudentId, subjectId: bigint): Promise<Array<Assignment>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getGradeAveragesBySubject(studentId: StudentId, subjectId: bigint): Promise<bigint>;
    getLessonAssignmentDetails(assignmentId: AssignmentId): Promise<[string, string, string, Time] | null>;
    getLessonAverageBySubject(studentId: StudentId, subjectId: bigint): Promise<bigint>;
    getLessonContent(lessonId: LessonId): Promise<string>;
    getOnboardingGuide(): Promise<OnboardingGuide>;
    getPreMadeLessons(): Promise<Array<PreMadeLesson>>;
    getPremiumAccessStatus(user: Principal): Promise<boolean>;
    getPublicationStatus(): Promise<PublicationStatus>;
    getReportCard(reportCardId: ReportCardId): Promise<ReportCard>;
    getStripeSessionStatus(sessionId: string): Promise<StripeSessionStatus>;
    getStudentAssignments(studentId: StudentId): Promise<Array<Assignment>>;
    getStudentReportCards(studentId: StudentId): Promise<Array<ReportCard>>;
    getSubjects(): Promise<Array<Subject>>;
    getUnpublishReason(): Promise<string | null>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    gradeAssignment(assignmentId: AssignmentId, grade: bigint): Promise<void>;
    grantPremiumAccess(user: Principal): Promise<void>;
    isCallerAdmin(): Promise<boolean>;
    isPublished(): Promise<boolean>;
    isStripeConfigured(): Promise<boolean>;
    isSubscriptionCancelled(user: Principal): Promise<boolean>;
    listAllLessonPlans(): Promise<Array<LessonPlan>>;
    publishApp(): Promise<void>;
    purchasePremiumAccess(): Promise<string>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    setStripeConfiguration(config: StripeConfiguration): Promise<void>;
    submitAssignment(assignmentId: AssignmentId, submission: string): Promise<void>;
    submitAssignmentWithGrade(assignmentId: AssignmentId, submission: string, grade: bigint): Promise<void>;
    transform(input: TransformationInput): Promise<TransformationOutput>;
    unpublishApp(reason: string): Promise<void>;
    viewLessonsByGrade(gradeLevel: GradeLevel): Promise<Array<LessonPlan>>;
}
import type { Assignment as _Assignment, AssignmentId as _AssignmentId, LessonId as _LessonId, PublicationStatus as _PublicationStatus, StripeSessionStatus as _StripeSessionStatus, StudentId as _StudentId, TeacherId as _TeacherId, Time as _Time, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async assignLessonToStudent(arg0: string, arg1: LessonId, arg2: string, arg3: Time, arg4: StudentId): Promise<AssignmentId> {
        if (this.processError) {
            try {
                const result = await this.actor.assignLessonToStudent(arg0, arg1, arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignLessonToStudent(arg0, arg1, arg2, arg3, arg4);
            return result;
        }
    }
    async cancelPremiumSubscription(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.cancelPremiumSubscription();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.cancelPremiumSubscription();
            return result;
        }
    }
    async createCheckoutSession(arg0: Array<ShoppingItem>, arg1: string, arg2: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.createCheckoutSession(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createCheckoutSession(arg0, arg1, arg2);
            return result;
        }
    }
    async createCustomLesson(arg0: string, arg1: Subject, arg2: GradeLevel, arg3: string): Promise<LessonId> {
        if (this.processError) {
            try {
                const result = await this.actor.createCustomLesson(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createCustomLesson(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async createLessonFromLibrary(arg0: LessonId): Promise<LessonId> {
        if (this.processError) {
            try {
                const result = await this.actor.createLessonFromLibrary(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createLessonFromLibrary(arg0);
            return result;
        }
    }
    async generateReportCard(arg0: StudentId): Promise<ReportCardId> {
        if (this.processError) {
            try {
                const result = await this.actor.generateReportCard(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.generateReportCard(arg0);
            return result;
        }
    }
    async getAllReportCardsForStudent(arg0: StudentId): Promise<Array<ReportCard>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllReportCardsForStudent(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllReportCardsForStudent(arg0);
            return result;
        }
    }
    async getAppMarketListing(): Promise<AppMarketListing> {
        if (this.processError) {
            try {
                const result = await this.actor.getAppMarketListing();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAppMarketListing();
            return result;
        }
    }
    async getAppStorePreview(): Promise<AppStorePreview> {
        if (this.processError) {
            try {
                const result = await this.actor.getAppStorePreview();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAppStorePreview();
            return result;
        }
    }
    async getAssignmentsBySubject(arg0: StudentId, arg1: bigint): Promise<Array<Assignment>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAssignmentsBySubject(arg0, arg1);
                return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAssignmentsBySubject(arg0, arg1);
            return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async getGradeAveragesBySubject(arg0: StudentId, arg1: bigint): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getGradeAveragesBySubject(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getGradeAveragesBySubject(arg0, arg1);
            return result;
        }
    }
    async getLessonAssignmentDetails(arg0: AssignmentId): Promise<[string, string, string, Time] | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getLessonAssignmentDetails(arg0);
                return from_candid_opt_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLessonAssignmentDetails(arg0);
            return from_candid_opt_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async getLessonAverageBySubject(arg0: StudentId, arg1: bigint): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getLessonAverageBySubject(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLessonAverageBySubject(arg0, arg1);
            return result;
        }
    }
    async getLessonContent(arg0: LessonId): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.getLessonContent(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLessonContent(arg0);
            return result;
        }
    }
    async getOnboardingGuide(): Promise<OnboardingGuide> {
        if (this.processError) {
            try {
                const result = await this.actor.getOnboardingGuide();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOnboardingGuide();
            return result;
        }
    }
    async getPreMadeLessons(): Promise<Array<PreMadeLesson>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPreMadeLessons();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPreMadeLessons();
            return result;
        }
    }
    async getPremiumAccessStatus(arg0: Principal): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.getPremiumAccessStatus(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPremiumAccessStatus(arg0);
            return result;
        }
    }
    async getPublicationStatus(): Promise<PublicationStatus> {
        if (this.processError) {
            try {
                const result = await this.actor.getPublicationStatus();
                return from_candid_PublicationStatus_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPublicationStatus();
            return from_candid_PublicationStatus_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async getReportCard(arg0: ReportCardId): Promise<ReportCard> {
        if (this.processError) {
            try {
                const result = await this.actor.getReportCard(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getReportCard(arg0);
            return result;
        }
    }
    async getStripeSessionStatus(arg0: string): Promise<StripeSessionStatus> {
        if (this.processError) {
            try {
                const result = await this.actor.getStripeSessionStatus(arg0);
                return from_candid_StripeSessionStatus_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStripeSessionStatus(arg0);
            return from_candid_StripeSessionStatus_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async getStudentAssignments(arg0: StudentId): Promise<Array<Assignment>> {
        if (this.processError) {
            try {
                const result = await this.actor.getStudentAssignments(arg0);
                return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStudentAssignments(arg0);
            return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async getStudentReportCards(arg0: StudentId): Promise<Array<ReportCard>> {
        if (this.processError) {
            try {
                const result = await this.actor.getStudentReportCards(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStudentReportCards(arg0);
            return result;
        }
    }
    async getSubjects(): Promise<Array<Subject>> {
        if (this.processError) {
            try {
                const result = await this.actor.getSubjects();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSubjects();
            return result;
        }
    }
    async getUnpublishReason(): Promise<string | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUnpublishReason();
                return from_candid_opt_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUnpublishReason();
            return from_candid_opt_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async gradeAssignment(arg0: AssignmentId, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.gradeAssignment(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.gradeAssignment(arg0, arg1);
            return result;
        }
    }
    async grantPremiumAccess(arg0: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.grantPremiumAccess(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.grantPremiumAccess(arg0);
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async isPublished(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isPublished();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isPublished();
            return result;
        }
    }
    async isStripeConfigured(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isStripeConfigured();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isStripeConfigured();
            return result;
        }
    }
    async isSubscriptionCancelled(arg0: Principal): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isSubscriptionCancelled(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isSubscriptionCancelled(arg0);
            return result;
        }
    }
    async listAllLessonPlans(): Promise<Array<LessonPlan>> {
        if (this.processError) {
            try {
                const result = await this.actor.listAllLessonPlans();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listAllLessonPlans();
            return result;
        }
    }
    async publishApp(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.publishApp();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.publishApp();
            return result;
        }
    }
    async purchasePremiumAccess(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.purchasePremiumAccess();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.purchasePremiumAccess();
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n19(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n19(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async setStripeConfiguration(arg0: StripeConfiguration): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setStripeConfiguration(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setStripeConfiguration(arg0);
            return result;
        }
    }
    async submitAssignment(arg0: AssignmentId, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.submitAssignment(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitAssignment(arg0, arg1);
            return result;
        }
    }
    async submitAssignmentWithGrade(arg0: AssignmentId, arg1: string, arg2: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.submitAssignmentWithGrade(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitAssignmentWithGrade(arg0, arg1, arg2);
            return result;
        }
    }
    async transform(arg0: TransformationInput): Promise<TransformationOutput> {
        if (this.processError) {
            try {
                const result = await this.actor.transform(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.transform(arg0);
            return result;
        }
    }
    async unpublishApp(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.unpublishApp(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.unpublishApp(arg0);
            return result;
        }
    }
    async viewLessonsByGrade(arg0: GradeLevel): Promise<Array<LessonPlan>> {
        if (this.processError) {
            try {
                const result = await this.actor.viewLessonsByGrade(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.viewLessonsByGrade(arg0);
            return result;
        }
    }
}
function from_candid_Assignment_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Assignment): Assignment {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_PublicationStatus_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PublicationStatus): PublicationStatus {
    return from_candid_variant_n15(_uploadFile, _downloadFile, value);
}
function from_candid_StripeSessionStatus_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _StripeSessionStatus): StripeSessionStatus {
    return from_candid_variant_n17(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfile_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): UserProfile {
    return from_candid_record_n10(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n12(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [[string, string, string, _Time]]): [string, string, string, Time] | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : from_candid_UserProfile_n9(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    role: _UserRole;
}): {
    name: string;
    role: UserRole;
} {
    return {
        name: value.name,
        role: from_candid_UserRole_n11(_uploadFile, _downloadFile, value.role)
    };
}
function from_candid_record_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    userPrincipal: [] | [string];
    response: string;
}): {
    userPrincipal?: string;
    response: string;
} {
    return {
        userPrincipal: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.userPrincipal)),
        response: value.response
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    lessonId: _LessonId;
    title: string;
    studentId: _StudentId;
    assignedBy: _TeacherId;
    completed: boolean;
    dueDate: _Time;
    description: string;
    grade: [] | [bigint];
    assignmentId: _AssignmentId;
    submission: [] | [string];
}): {
    lessonId: LessonId;
    title: string;
    studentId: StudentId;
    assignedBy: TeacherId;
    completed: boolean;
    dueDate: Time;
    description: string;
    grade?: bigint;
    assignmentId: AssignmentId;
    submission?: string;
} {
    return {
        lessonId: value.lessonId,
        title: value.title,
        studentId: value.studentId,
        assignedBy: value.assignedBy,
        completed: value.completed,
        dueDate: value.dueDate,
        description: value.description,
        grade: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.grade)),
        assignmentId: value.assignmentId,
        submission: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.submission))
    };
}
function from_candid_variant_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    published: {
        publicationTime: _Time;
    };
} | {
    unpublished: {
        reason: string;
    };
}): {
    __kind__: "published";
    published: {
        publicationTime: Time;
    };
} | {
    __kind__: "unpublished";
    unpublished: {
        reason: string;
    };
} {
    return "published" in value ? {
        __kind__: "published",
        published: value.published
    } : "unpublished" in value ? {
        __kind__: "unpublished",
        unpublished: value.unpublished
    } : value;
}
function from_candid_variant_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    completed: {
        userPrincipal: [] | [string];
        response: string;
    };
} | {
    failed: {
        error: string;
    };
}): {
    __kind__: "completed";
    completed: {
        userPrincipal?: string;
        response: string;
    };
} | {
    __kind__: "failed";
    failed: {
        error: string;
    };
} {
    return "completed" in value ? {
        __kind__: "completed",
        completed: from_candid_record_n18(_uploadFile, _downloadFile, value.completed)
    } : "failed" in value ? {
        __kind__: "failed",
        failed: value.failed
    } : value;
}
function from_candid_vec_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Assignment>): Array<Assignment> {
    return value.map((x)=>from_candid_Assignment_n4(_uploadFile, _downloadFile, x));
}
function to_candid_UserProfile_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserProfile): _UserProfile {
    return to_candid_record_n20(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_record_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    role: UserRole;
}): {
    name: string;
    role: _UserRole;
} {
    return {
        name: value.name,
        role: to_candid_UserRole_n1(_uploadFile, _downloadFile, value.role)
    };
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
